#!/usr/bin/python

import os
import sys
import re

myfiles = [     
                "nfilemanagerimpl.cpp", 
                "nfilemanagerimpl.hx", 
                "nosfilemanagerimpl.cpp", 
                "nosfilemanagerimpl.hx", 
                "nosfilemanager.hi", 
                "nosfileimpl.cpp", 
                "nosfileimpl.hx", 
                "nosdirectoryimpl.cpp", 
                "nosdirectoryimpl.hx", 
                "ngi3filemanager.h", 
                "ngi3file.h", 
                "ngi3directory.h", 
          ]

for line in sys.stdin:
    if line[-1] == '\n': line = line[:-1]
    for myfile in myfiles:
        if re.search( myfile, line ) and not re.search( "svn", line ):
            print line

